import StyleDictionary from "style-dictionary";
import type { TransformedToken } from "style-dictionary";

import { colorTokens } from "./src/colors.ts";
import { motionTokens } from "./src/motion.ts";
import { radiiTokens } from "./src/radii.ts";
import { spacingTokens } from "./src/spacing.ts";
import { typographyTokens } from "./src/typography.ts";

// CSS 変数名を生成（light/dark プレフィックスは除去）
function toVar(path: string[]): string {
  const stripped = ["light", "dark"].includes(path[0]!) ? path.slice(1) : path;
  return `  --eni-${stripped.join("-")}`;
}

// トークンの value を取得（Style Dictionary 変換後）
function getValue(token: TransformedToken): string {
  return String(token.value ?? (token as Record<string, unknown>)["$value"] ?? "");
}

// カスタムフォーマット: ライト/ダーク両対応 CSS Variables
StyleDictionary.registerFormat({
  name: "css/eni-dual-theme",
  format: ({ dictionary }) => {
    const all = dictionary.allTokens;

    const staticTokens = all.filter((t) => !["light", "dark"].includes(t.path[0]!));
    const lightTokens  = all.filter((t) => t.path[0] === "light");
    const darkTokens   = all.filter((t) => t.path[0] === "dark");

    const lines: string[] = [
      "/* Generated by @eni/tokens — do not edit manually */",
      "",
      ":root {",
      ...staticTokens.map((t) => `${toVar(t.path)}: ${getValue(t)};`),
      ...lightTokens.map((t)  => `${toVar(t.path)}: ${getValue(t)};`),
      "}",
      "",
      "[data-theme=\"dark\"] {",
      ...darkTokens.map((t) => `${toVar(t.path)}: ${getValue(t)};`),
      "}",
      "",
    ];

    return lines.join("\n");
  },
});

// JS/TS 用カスタムフォーマット: CSS 変数参照のオブジェクトを出力
StyleDictionary.registerFormat({
  name: "js/eni-variables",
  format: ({ dictionary }) => {
    const all = dictionary.allTokens;

    // 重複除去: light/dark は同じ変数名になるので light のみ使用
    const seen = new Set<string>();
    const entries: string[] = [];

    for (const t of all) {
      if (t.path[0] === "dark") continue; // dark は light と同名なのでスキップ
      const varName = toVar(t.path).trim();
      if (seen.has(varName)) continue;
      seen.add(varName);
      entries.push(`  "${varName.replace("--eni-", "")}": "${varName}"`);
    }

    return [
      "/* Generated by @eni/tokens — do not edit manually */",
      "export const tokens = {",
      entries.join(",\n"),
      "} as const;",
      "",
      "export type TokenKey = keyof typeof tokens;",
      "",
    ].join("\n");
  },
});

// カスタム transform group（カラー変換をスキップ）
StyleDictionary.registerTransformGroup({
  name: "css/eni",
  transforms: ["attribute/cti", "name/kebab"],
});

StyleDictionary.registerTransformGroup({
  name: "js/eni",
  transforms: ["attribute/cti", "name/kebab"],
});

const sd = new StyleDictionary({
  tokens: {
    // テーマ依存: カラー（light/dark 両方）
    ...colorTokens,
    // テーマ非依存
    ...spacingTokens,
    ...typographyTokens,
    ...motionTokens,
    ...radiiTokens,
  },
  platforms: {
    css: {
      transformGroup: "css/eni",
      buildPath: "build/css/",
      files: [
        {
          destination: "tokens.css",
          format: "css/eni-dual-theme",
        },
      ],
    },
    js: {
      transformGroup: "js/eni",
      buildPath: "build/js/",
      files: [
        {
          destination: "index.mjs",
          format: "js/eni-variables",
        },
      ],
    },
    figma: {
      transformGroup: "css/eni",
      buildPath: "build/",
      files: [
        {
          destination: "figma.json",
          format: "json/nested",
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log("✓ @eni/tokens build complete");
